#!/usr/bin/env python3
"""Lets you type `./alarm set 7:30` instead of `python3 -m alarmclock set 7:30`."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from alarmclock.cli import main  # noqa: E402

sys.exit(main())
